osx_image: xcode7.3

language: node_js
node_js: "6"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - graphicsmagick
      - icnsutils
      - rpm

notifications:
  email: false

dist: trusty
sudo: false

deploy:
  provider: script
  script: if [ ! -z "$TRAVIS_TAG" ]; then npm run release -- --ia32 --x64 --prerelease; fi
  on:
    tags: true