matrix:
  include:
    - os: linux
      dist: trusty
      language: node_js
      node_js: "6"
    - os: osx
      osx_image: xcode7.3
      language: node_js
      node_js: "6"

addons:
  apt:
    packages:
      - graphicsmagick
      - icnsutils
      - rpm

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release -- --ia32 --x64 --prerelease
  on:
    tags: true