osx_image: xcode7.3

language: node_js
node_js: "6"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - graphicsmagick
      - icnsutils
      - rpm

notifications:
  email: false

dist: trusty
sudo: false

after_success:
  # Only build releases on tags
  - if [ ! -z "$TRAVIS_TAG" ]; then npm run release -- --prerelease; fi