environment:
  nodejs_version: "6"

platform: x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - npm test

build: off

build_script:
  - npm run release -- --ia32 --x64 --prerelease