environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

build: off

on_success:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        npm run release -- --prerelease
      }